Add "Firmware" chapter
chargebyte/chargebyte-docs pull request #1
Opened 2024-06-18 05:30 UTC by mooraby

2024-06-18 07:33 UTC, t-mon requested changes

2024-06-18 07:33 UTC, t-mon commented on docs/source/firmware.rst
> +* Every time you insert the USB flash drive or perform a reboot, we prevent re-execution of your customized :code:`autorun.sh` script if it has not been changed. This does not depend on the success o
`we prevent re-execution of`
 
 `a re-execution of the ... will be prevented if there are no changes`
 
 > Overall I think the documentation should not speak in "we" and "you" as two parties. Just a tought.

2024-06-18 07:33 UTC, t-mon commented on docs/source/firmware.rst
> +The username- password combination required for login is:
username and password combination

2024-06-18 07:33 UTC, t-mon commented on docs/source/firmware.rst
> +This is a generic password, so it is required to be changed by the customer!
this **must** be changed by the customer!

Somehow make this important, red or a Info box.

2024-06-18 07:45 UTC, lategoodbye requested changes

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +Charge Control C is shipped with pre-flashed firmware including the EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem. The shipped firmware was created usi
I think this only half of the truth. In the future the Charge Control C can have a pre-flashed EVerest, but this is not always the case. So i think we should tell the current state not the ideal future.

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +#. Download chargebyte's digital certificate found on chargebyte's website which is used to validate firmware update images distributed by chargebyte GmbH.
Too many chargebyte

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +#. Use the latest firmware update image we provided or download it from the product's section on chargebyte's website https://chargebyte.com/products/charging-station-communication/charge-control-c.
Yes, this would be hopefully the goal, but doesn't apply for now. Maybe this needs a decision from PO

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +Charge Control C is shipped with SSH (Secure Shell) service running on the bridge interface, i.e. Ethernet and mains powerline interface (only Charge Control 300). It allows you to connect to Charge
Please drop the second SSH in the last sentence

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +#. Download the firmware update image file onto your workstation. The file size is about 70 MB in current standard configuration.
Since we deploy development images please use a more realistic file size

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +#. Wait until the whole firmware update and reboot process is finished - it takes up to 5 minutes.
I'm not sure but maybe the necessary update time must be increased

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +#. Backup all your own implementation and configuration files if necessary.
databases ?

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +However, it is worth mentioning that the partitions are not synchronized. Thus, if one rootfs is customized, such as by integrating custom software applications, the other partition remains unaffecte
I'm not aware of the current EVerest migration steps, but the /var/lib/everest (database stuff) and certificates seems to missed here

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +* You need to determine how your software components will interact with the EVerest stack. You can develop your software as an EVerest module and use one of the EVerest interfaces for interaction. Al
s/secion/section

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +* Develop your customer software on your local PC Linux environment, where you can use a compiler, debugger etc. you are familiar with. If the software you developed does not depend on specific hardw
I think it would be helpful to provide a link to EVerest docs about SIL

2024-06-18 07:45 UTC, lategoodbye commented on docs/source/firmware.rst
> +Charge Control C is shipped with pre-flashed firmware including the EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem. The shipped firmware was created usi
additional EVerest modules = EVerest BSP?

I think this is the first place where we need to introduce the meaning of EVerest BSP

2024-06-18 08:41 UTC, mooraby commented on docs/source/firmware.rst
> +      $ sudo apt-get install build-essential automake libtool libdbus-1-dev libglib2.0-dev libcurl3-dev libssl-dev libjson-glib-dev
I tried to select it in the output document (three mouse clicks) and copy it, and it was copied without the leading $. But adding the copy button is a good idea. I will check how to embed it.

2024-06-18 08:49 UTC, mooraby commented on docs/source/firmware.rst
> +Charge Control C is shipped with pre-flashed firmware including the EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem. The shipped firmware was created usi
When writing the documentation, I thought of it as it mirros a state in the future, which means in the future that we will only pre-flash EVerest images and not our charging stack. If you think that this was a wrong assumption, let me know.

2024-06-18 08:51 UTC, mooraby commented on docs/source/firmware.rst
> +#. Use the latest firmware update image we provided or download it from the product's section on chargebyte's website https://chargebyte.com/products/charging-station-communication/charge-control-c.
Part of this documentation only makes sense if the a firmware image can be downloaded from our website.

2024-06-18 08:52 UTC, mooraby commented on docs/source/firmware.rst
> +#. Download the firmware update image file onto your workstation. The file size is about 70 MB in current standard configuration.
The number written here was 30MB which was our non-developer truffle image. The 70 MB is our non-developer EVerest image, which should be the one delivered/found on the website.

2024-06-18 08:54 UTC, mooraby commented on docs/source/firmware.rst
> +#. Wait until the whole firmware update and reboot process is finished - it takes up to 5 minutes.
I did not check it but I think the 5 minutes are roughly ok (RAUC install process + reboot + EVerest starting)

2024-06-18 08:59 UTC, lategoodbye commented on docs/source/firmware.rst
> +Charge Control C is shipped with pre-flashed firmware including the EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem. The shipped firmware was created usi
I think this future will be in the next year or later. The pre-flashed EVerest will have a separate order code, but we don't stop shipping Truffle images for now.

2024-06-18 08:59 UTC, mooraby commented on docs/source/firmware.rst
> +Charge Control C is shipped with pre-flashed firmware including the EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem. The shipped firmware was created usi
It is not only the EVerest BSP that is added to the charging stack, there are other modules like GpioRgbLed etc...This is why I did not write BSP or HAL

2024-06-18 09:31 UTC, lategoodbye commented on docs/source/firmware.rst
> +#. Download the firmware update image file onto your workstation. The file size is about 70 MB in current standard configuration.
Again i think we should describe the current state, not the distant future.

2024-06-18 09:38 UTC, lategoodbye commented on docs/source/firmware.rst
> +Charge Control C is shipped with pre-flashed firmware including the EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem. The shipped firmware was created usi
Okay, let me explain my intention independent from this chapter. We need to explain somewhere the meaning of EVerest BSP and that we provide this in the firmware.

2024-06-18 09:42 UTC, lategoodbye commented on docs/source/firmware.rst
> +Charge Control C is shipped with pre-flashed firmware including the EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem. The shipped firmware was created usi
Please image the following use cases:
Use case 1 (new customer):
- customer orders Charge Control C with included EVerest stack

Use case 2 (Truffle customer):
- customer already has a Charge Control C with Truffle stack and wants to migrate to EVerest stack

2024-06-18 10:43 UTC, mooraby commented on docs/source/firmware.rst
> +Charge Control C is shipped with pre-flashed firmware including the EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem. The shipped firmware was created usi
Yes this is more part of chapter 5 (EVerest charging stack)

2024-06-18 11:42 UTC, lategoodbye commented on docs/source/firmware.rst
> +#. Use the latest firmware update image we provided or download it from the product's section on chargebyte's website https://chargebyte.com/products/charging-station-communication/charge-control-c.
tbd with PO

2024-06-19 05:46 UTC, mooraby commented on docs/source/firmware.rst
> +      $ sudo apt-get install build-essential automake libtool libdbus-1-dev libglib2.0-dev libcurl3-dev libssl-dev libjson-glib-dev
So I added the copy button, but now the dollar sign is copied as part of the commands. I am a little unsure what should be done. What is your opinion?

2024-06-19 06:27 UTC, mooraby commented on docs/source/firmware.rst
> +   #. It is checked whether the signature of :code:`autorun.sh` is valid against the current certificate found in :code:`/etc/rauc/keyring.pem`. Remember, that this usually now contains your CA certi
Proofreading online suggests "Remember, this now usually contains your CA certificate"

2024-06-19 06:30 UTC, mooraby commented on docs/source/firmware.rst
> +* Every time you insert the USB flash drive or perform a reboot, we prevent re-execution of your customized :code:`autorun.sh` script if it has not been changed. This does not depend on the success o
Although I agree with you, sometimes it is inevitable to use such wording. I will try to rephrase but I do not promise that I will be able to totally get rid of it.

2024-06-19 06:36 UTC, mooraby commented on docs/source/firmware.rst
> +This is a generic password, so it is required to be changed by the customer!
added **MUST** bold and capital letters

2024-06-19 06:45 UTC, t-mon commented on docs/source/firmware.rst
> +      $ sudo apt-get install build-essential automake libtool libdbus-1-dev libglib2.0-dev libcurl3-dev libssl-dev libjson-glib-dev
I personally would prefer to remove the `$` signs, since the code section and the commands should make it clear enough. If someone understands that $ means shell, he probably understands that those are shell commands.

Also the copy button would than make no sense any more.

2024-06-19 06:55 UTC, mooraby commented on docs/source/firmware.rst
> +#. Download the firmware update image file onto your workstation. The file size is about 70 MB in current standard configuration.
Removed the sentence

2024-06-19 06:58 UTC, mooraby commented on docs/source/firmware.rst
> +Charge Control C is shipped with pre-flashed firmware including the EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem. The shipped firmware was created usi
I think this should maybe part of chapter 5?

2024-06-19 09:40 UTC, mooraby commented on docs/source/firmware.rst
> +Charge Control C is shipped with pre-flashed firmware including the EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem. The shipped firmware was created usi
Charge Control C is shipped with pre-flashed firmware including one of the following charging stacks:

* chargebyte's proprietary charging stack.
* EVerest charging stack along with additional EVerest modules e.g., CbTarragonDriver, CbSystem.

2024-06-19 10:09 UTC, lategoodbye commented on docs/source/firmware.rst
> +This assumes that the first step has successfully ended, and the file :code:`/etc/raun/keyring.pem` now contains your CA certificate. However, this will also work later at any time, as long as the CA
s/raun/rauc

2024-06-20 09:05 UTC, lategoodbye commented on docs/source/firmware.rst
> +#. Use the latest firmware update image we provided or download it from the product's section on chargebyte's website https://chargebyte.com/products/charging-station-communication/charge-control-c.
In case this is the only open point, i suggest to merge the current state and fix it later.

2024-06-20 09:08 UTC, lategoodbye approved these changes

2024-06-20 09:24 UTC, t-mon approved these changes

2024-06-20 11:35 UTC, merged