Add documentation for "Development" chapter
chargebyte/chargebyte-docs pull request #10
Opened 2024-06-25 09:34 UTC by mooraby

2024-06-25 11:46 UTC, barsnick requested changes
Good job.

2024-06-25 11:46 UTC, barsnick commented on docs/source/development.rst
> +The EVerest documentation explains the `modules in details <https://everest.github.io/nightly/general/04_detail_module_concept.html>`_
The fixed term is to do something "[in detail](https://dictionary.cambridge.org/dictionary/english/in-detail)":
```suggestion
The EVerest documentation explains the `modules in detail <https://everest.github.io/nightly/general/04_detail_module_concept.html>`_
```

2024-06-25 11:46 UTC, barsnick commented on docs/source/development.rst
> +      SRC_URI = "git://github.com/my_module.git;branch=master"
Reality check: A GitHub URI will also include a user/namespace. Let's also default to `main` branch 😉:
```suggestion
      SRC_URI = "git://github.com/my_org/my_module.git;branch=main"
```

2024-06-25 11:46 UTC, barsnick commented on docs/source/development.rst
> +      }
The `do_install()` section obviously implies that `my_module`'s cmake does not have a proper `install`directive (otherwise it's automatic in bitbake, and everest-cmake also takes care of this). But we'll leave this up to the customer to find out, they have plenty of good links to the Yocto docs.

2024-06-25 11:46 UTC, barsnick commented on docs/source/development.rst
> +Crosscompiling for Tarragon
I prefer the more common use with a dash `-` as a separator (also in other places):
```suggestion
Cross-compiling for Tarragon
```

2024-06-25 11:46 UTC, barsnick commented on docs/source/development.rst
> +for Tarragon and include it in the image. A pre-requisite for this is to have the last firmware image,
last -> latest, perhaps?
```suggestion
for Tarragon and include it in the image. A pre-requisite for this is to have the latest firmware image,
```

2024-06-25 11:46 UTC, barsnick commented on docs/source/development.rst
> +      sudo apt install build-essential libc6-armhf-cross libc6-dev-armhf-cross binutils-arm-linux-gnueabihf gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
This only works on Debian-like systems, so basically Debian and Ubuntu. Actually, other (non-Debian) distributions don't even provide proper cross-build environments!

2024-06-25 11:46 UTC, barsnick commented on docs/source/development.rst
> +      cd my-module
Judging from the Git URI example, this will be `my_module`. But this might not matter.

2024-06-25 11:46 UTC, barsnick commented on docs/source/development.rst
> +      file /dist/libexec/everest/modules/MyModule/MyModule
Not an absolute directory:
```suggestion
      file ./dist/libexec/everest/modules/MyModule/MyModule
```

2024-06-25 11:46 UTC, barsnick commented on docs/source/development.rst
> +#. The resulting binary and manifest file can be copied to the root filesystem.
```suggestion
#. The resulting binary and manifest file can be copied to the previously mounted root filesystem.
```

2024-06-25 13:44 UTC, barsnick commented on docs/source/development.rst
> +   called "`chargebyte-bsp <https://github.com/chargebyte/chargebyte-bsp/tree/kirkstone-everest>`_".
Yes, please mention that we are currently based on kirkstone. Otherwise, this is only implied by the URL.

2024-06-26 04:52 UTC, mooraby commented on docs/source/development.rst
> +      }
It is just an example to tell the customer that they can overwrite some bitbake functions

2024-06-26 05:09 UTC, mooraby commented on docs/source/development.rst
> +      cd my-module
changed all to my-module instead

2024-06-26 06:48 UTC, t-mon requested changes
Just some suggestions, nice chapter :-)

2024-06-26 06:48 UTC, t-mon commented on docs/source/development.rst
> +   on an Ubuntu 20.04 or later Linux distribution.)
is it really 20.04 or should we use 24.04 by now...it should not make any difference?

2024-06-26 06:48 UTC, t-mon commented on docs/source/development.rst
> +#. A recipe file is needed to build the module. The recipe file is a file with the extension :code:`.bb` and
Maybe get rid if the double file here:

`A recipe is a file with the extension ....`

2024-06-26 06:48 UTC, t-mon commented on docs/source/development.rst
> +      LICENSE = "CLOSED"
Maybe use also Apache2 in the example?

2024-06-26 06:48 UTC, t-mon commented on docs/source/development.rst
> +#. On an Ubuntu or Debian Linux distribution, install the cross-compilers for Tarragon.
On an Ubuntu or Debian `based` Linux distribution

2024-06-26 06:48 UTC, t-mon commented on docs/source/development.rst
> +      sudo mkdir -p /tmp/rootfs
The default location for mounting would be `/mnt/` or is there a special reason for mounting into a tmpfs location?

2024-06-26 07:10 UTC, mooraby commented on docs/source/development.rst
> +   on an Ubuntu 20.04 or later Linux distribution.)
AFAIK we only tested it until 22.04.. for instance our Jenkins server is definitely not 24.04

2024-06-26 07:14 UTC, mooraby commented on docs/source/development.rst
> +      sudo mkdir -p /tmp/rootfs
No special reason

2024-06-26 07:32 UTC, t-mon approved these changes
Nice

2024-06-26 07:35 UTC, lategoodbye approved these changes

2024-06-26 07:44 UTC, merged