Adjust the README.rst file
chargebyte/chargebyte-docs pull request #11
Opened 2024-06-25 14:27 UTC by FaHaGit

2024-06-25 15:15 UTC, barsnick requested changes

2024-06-25 15:15 UTC, barsnick commented on README.rst
> +Building the Documentation locally:
Not sure about which of the two, but either "Documentation" needs to be non-capitalized, or "locally" capitalized.

2024-06-25 15:15 UTC, barsnick commented on README.rst
> +See the LICENSE file for license rights and limitations (MIT).
Our license isn't MIT.

2024-06-26 05:42 UTC, martinlukas84 approved these changes

2024-06-26 06:24 UTC, t-mon approved these changes

2024-06-26 06:33 UTC, merged