Add "Firmware Update" section to getting started guide (refs ALPHA-2672)
chargebyte/chargebyte-docs pull request #13
Opened 2024-07-01 13:08 UTC by FaHaGit

2024-07-01 13:37 UTC, barsnick requested changes

2024-07-01 13:37 UTC, barsnick commented on docs/source/firmware.rst
> +  file migrations/changes are applied, so this might break your setup - especially when EVerest
We have integrated some migrations, as documented in the release notes. This will start with EVerest 2024.6.0.

2024-07-01 13:37 UTC, barsnick commented on docs/source/firmware.rst
> +  files are preserved, see the latest Quick start guide for details. However, no automatic config
A link to the Quick Start Guide would be good.

Also, ich "Quick" has a capital 'Q', the rest should be capitalized as well, to show that it's the proper title.

2024-07-01 13:37 UTC, barsnick commented on docs/source/firmware.rst
> +  by chargebyte. They are intended for developers who want to test new features or changes before
They are also intended for application development, containing development tools and libraries.

2024-07-01 13:37 UTC, barsnick commented on docs/source/getting_started.rst
> +content of the configuration file, you will see that there is only a reference to the
there is -> it is

(Yes, this passed the previous review. 😉)

2024-07-01 13:37 UTC, barsnick commented on docs/source/getting_started.rst
> +uses by default "/etc/everest/config.yaml" as a configuration setup. If you take a look at the
Word order: that by default uses "/etc..."...

2024-07-01 13:42 UTC, FaHaGit commented on docs/source/firmware.rst
> +  file migrations/changes are applied, so this might break your setup - especially when EVerest
I will check

2024-07-01 13:43 UTC, FaHaGit commented on docs/source/firmware.rst
> +  files are preserved, see the latest Quick start guide for details. However, no automatic config
The quick start reference should be removed at all

2024-07-01 14:31 UTC, lategoodbye commented on docs/source/firmware.rst
> +  files are preserved, see the latest Quick start guide for details. However, no automatic config
I agree with @FaHaGit

2024-07-02 04:49 UTC, FaHaGit commented on docs/source/firmware.rst
> +  file migrations/changes are applied, so this might break your setup - especially when EVerest
I think the description should be part of the 0.11.0 release right?

2024-07-02 06:25 UTC, barsnick commented on docs/source/firmware.rst
> +  file migrations/changes are applied, so this might break your setup - especially when EVerest
I'm sorry, that's correct. They will be in the next release. So this info would be incorrect when we merge this doc PR for 0.10.0.

2024-07-02 06:51 UTC, barsnick commented on docs/source/firmware.rst
> +  file migrations/changes are applied, so this might break your setup - especially when EVerest
Let's change this in a branch for 0.11.0, not here.

2024-07-02 06:52 UTC, barsnick approved these changes

2024-07-02 08:54 UTC, lategoodbye requested changes

2024-07-02 08:54 UTC, lategoodbye commented on docs/source/firmware.rst
> +  Linux configuration files (SSH keys, hostname and similar) are kept when switching between EVerest
I think the most import point: are the passwort kept or set to default

2024-07-02 08:54 UTC, lategoodbye commented on docs/source/troubleshooting.rst
>  Yes it is, but be aware that the configuration and database files will not be converted.
Please explicitly mention the keyring problematic here, in the answer. The final reference below should the rest.

2024-07-03 14:08 UTC, lategoodbye approved these changes

2024-07-04 04:31 UTC, merged