Add hardware chapter to project (refs EVEREST-929)
chargebyte/chargebyte-docs pull request #2
Opened 2024-06-18 08:23 UTC by martinlukas84

2024-06-18 08:52 UTC, lategoodbye requested changes

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/_static/images/2021-04-Button-final.png
This applies only to Truffle, please drop

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/_static/images/Certified_by_Gridware_OCPP.png
This applies only to Truffle, please drop

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/_static/images/be.energised_certified_logo_1.6.svg
This applies only to Truffle, please drop

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/hardware.rst
> +    * - StrongLink SL032 (with customized Modbus protocol)
We need to clarify that the default StrongLink SL032 is not supported yet

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/hardware.rst
> +    * - PN532
Does the PN532 really have a Modbus interface?

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/hardware.rst
> +pluglock motors. Therefore, it's possible to adapt voltage threshold values used to detect locked and unlocked positions.
We should describe the CbTarragonPluglock more beginner friendly:
- What really needs to be adapted in this general purpose interface?
- How can i achieve "without feedback"?
- Settings table for know locking motors

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/hardware.rst
> +      - /sys/class/gpio/gpio119
Since we implemented all GPIO handling based on the GPIO chardev, we should reference the line names and not the legacy GPIO interface

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/hardware.rst
> +To use the digital inputs in Linux userspace, the corresponding GPIO may need to be exported and set to correct direction.
This needs to be adapted to chardev / libgpio

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/hardware.rst
> +      -	/sys/class/gpio/gpio89
Since we implemented all GPIO handling based on the GPIO chardev, we should reference the line names and not the legacy GPIO interface

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/hardware.rst
> +    echo "out" > /sys/class/gpio/gpio89/direction
This needs to be adapted to chardev / libgpio

2024-06-18 08:52 UTC, lategoodbye commented on docs/source/hardware.rst
> +**Certifications**
Please drop the whole section, this should be replace with a link to EVerest OCPP documencation if really required

2024-06-18 12:43 UTC, mhei commented on docs/source/hardware.rst
> +*******************
I'm unsure whether .rst enforce or requires here rules regarding empty lines. Personally, I would always have an empty line after each heading. And this should be consistent throughout the whole repo.

2024-06-19 04:56 UTC, martinlukas84 commented on docs/source/hardware.rst
> +*******************
No there are no rules regarding empty lines after header. I tested.

2024-06-19 05:29 UTC, martinlukas84 commented on docs/source/hardware.rst
> +**Certifications**
I will drop whole section!

2024-06-19 05:31 UTC, martinlukas84 commented on docs/source/hardware.rst
> +    * - PN532
Will be removed from table

2024-06-19 11:50 UTC, lategoodbye commented on docs/source/hardware.rst
> +SW2 is reserved for future use and is not populated at the moment.
Yes, it's reserved for future use because EVerest BSP doesn't handle it, but it's still populated on the hardware

2024-06-19 11:55 UTC, lategoodbye commented on docs/source/hardware.rst
> +In module PowermeterIskra_WM3M4C, the modbus addresses are hardcoded and can not be change.
Since we didn't plan to change the situation, we better provide the hardcoded address here.

2024-06-19 12:00 UTC, lategoodbye commented on docs/source/hardware.rst
> +    root@tarragon:˜$ gpioget --by-name DIGITAL_IN_2
I'm fine with in general, but i suggest to add --as-is in order to avoid unexpected direction changes

2024-06-19 12:02 UTC, lategoodbye commented on docs/source/hardware.rst
> +To use the digital inputs in Linux userspace, use the *libgpio* tools (i.e. gpioinfo, gpioget, ...).
s/libgpio/libgpiod

2024-06-19 12:21 UTC, lategoodbye commented on docs/source/hardware.rst
> +    * - StrongLink SL032 (with customized Modbus protocol)
Thanks for adding the note, but i don't think this is fool proof. I would suggest to replace the current entry with the following:

- StrongLink SL032 Modbus (propietary UART protocol is not supported)

2024-06-19 12:24 UTC, lategoodbye commented on docs/source/hardware.rst
> +Charging stack.
The second sentence is not clear. We need to clarify which one is supported.

2024-06-19 13:40 UTC, mhei commented on docs/source/hardware.rst
> +For SunSpec (PowermeterBSM) compatible meters the configuration can be found on
The wording might be confusing... This specific power meter is SunSpec compatible, but you cannot use a random SunSpec power meter with this module. This module is specific for this Bauer product.

2024-06-20 05:24 UTC, martinlukas84 commented on docs/source/hardware.rst
> +SW2 is reserved for future use and is not populated at the moment.
Ah. This was a copy paste issue.

2024-06-20 05:36 UTC, martinlukas84 commented on docs/source/hardware.rst
> +To use the digital inputs in Linux userspace, use the *libgpio* tools (i.e. gpioinfo, gpioget, ...).
I don't understand. I assume libgpio has to be replaced by libgpiod?

2024-06-20 07:20 UTC, lategoodbye commented on docs/source/hardware.rst
> +To use the digital inputs in Linux userspace, use the *libgpio* tools (i.e. gpioinfo, gpioget, ...).
Sorry, i was in kernel developer mode. Yes, the "d" was just missing.

2024-06-20 09:01 UTC, lategoodbye approved these changes

2024-06-21 04:08 UTC, merged