Update FAQ regarding ISO 15118-20
chargebyte/chargebyte-docs pull request #20
Opened 2024-11-12 08:54 UTC by FaHaGit

2024-12-09 10:47 UTC, lategoodbye commented on docs/source/troubleshooting.rst
> +Please not that it is currently not possible to support ISO 15118-20 together with the other
I think the consequences for our customers are not clear (Do I need two different firmware versions, two images, two configurations?) Except of this I'm fine.

2024-12-10 11:18 UTC, FaHaGit commented on docs/source/troubleshooting.rst
> +Please not that it is currently not possible to support ISO 15118-20 together with the other
Thank you for the feedback, I will take that into account

2024-12-10 13:29 UTC, barsnick requested changes

2024-12-10 13:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +Please not that it is currently not possible to support ISO 15118-20 together with the other
Typo: note
```suggestion
Please note that it is currently not possible to support ISO 15118-20 together with the other
```

2024-12-10 13:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +protocols DIN 70121 and ISO15118-2. This is due to architectural reasons and will be fixed in a future
Didn't we also include the IsoMux module? So basically, it should work, though completely untested by us.

2024-12-10 14:35 UTC, FaHaGit commented on docs/source/troubleshooting.rst
> +protocols DIN 70121 and ISO15118-2. This is due to architectural reasons and will be fixed in a future
You are right. But we have currently no configuration for it.

2024-12-10 14:38 UTC, lategoodbye commented on docs/source/troubleshooting.rst
> +protocols DIN 70121 and ISO15118-2. This is due to architectural reasons and will be fixed in a future
In this case i suggest to drop the last two sentences.

2024-12-12 08:13 UTC, merged