Add Troubleshooting & FAQ chapter
chargebyte/chargebyte-docs pull request #3
Opened 2024-06-20 10:12 UTC by lategoodbye

2024-06-20 10:29 UTC, t-mon requested changes

2024-06-20 10:29 UTC, t-mon commented on docs/source/troubleshooting.rst
> +How can i access the EVerest admin panel on Charge Control C?
`s/i/I/g`

2024-06-20 10:29 UTC, t-mon commented on docs/source/troubleshooting.rst
> +How can i use CAN with Charge Control C?
`s/i/I/g`

2024-06-20 10:29 UTC, t-mon commented on docs/source/troubleshooting.rst
> +use your development PC to setup your configuration file or just use a plain text editor.
Suggestion: `Please use your development environment ...`

2024-06-20 10:29 UTC, t-mon commented on docs/source/troubleshooting.rst
> +How do i set up OCPP 2.0.1 on Charge Control C with EVerest?
`s/i/I/g`

2024-06-20 10:29 UTC, t-mon commented on docs/source/troubleshooting.rst
> +Unfortunately there some manual steps on a development PC necessary. At first checkout libocpp
Unfortunately`,` there `are` some ....

2024-06-20 10:29 UTC, t-mon commented on docs/source/troubleshooting.rst
> +if is not already done and change into OCPP 2.0.1 config directory:
Suggestion to simplify the sentence:
`At first checkout the libocpp and change into the OCPP 2.0.1 config directory:`

2024-06-20 10:29 UTC, t-mon commented on docs/source/troubleshooting.rst
> +After that we can create device model database and insert the configuration:
`you` can create...

Otherwise you switch between we and you within one section.

2024-06-20 10:29 UTC, t-mon commented on docs/source/troubleshooting.rst
> +   scp device_model_storage.db root@169.254.12.53:/var/lib/everest/ocpp201
suggestion: `root@<ip-address>:/var/...`

2024-06-20 10:29 UTC, t-mon commented on docs/source/troubleshooting.rst
> +Finally make sure DeviceModelDatabasePath in your EVerest configuration points to
make sure `the` DeviceModelDatabasePath in your ...

2024-06-21 07:48 UTC, t-mon approved these changes

2024-06-21 08:20 UTC, lategoodbye commented
Since the pull request is against the wrong branch, close this and reopen a new one.

2024-06-21 08:20 UTC, closed without merging