Add documentation for "EVerest charging stack" chapter
chargebyte/chargebyte-docs pull request #5
Opened 2024-06-20 11:40 UTC by mooraby

2024-06-20 12:51 UTC, lategoodbye requested changes

2024-06-20 12:51 UTC, lategoodbye commented on docs/source/_static/files/bsp-only.yaml
> +# This example configuration can be used as bare minimum starting point:
Since this is now official documentation, this should explain what we mean with "minimum starting point" here or in the referencing chapter:

- IEC 61851 / AC basic charging
- 1 connector with a fixed cable
- CP state D is rejected
- 1 contactor for 3 phase
- no phase switching

2024-06-20 12:51 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +This is the Hardware Abstraction Layer (HAL) for Charge Control C in EVerest. It implements the `evse_board_support <https://github.com/EVerest/everest-core/blob/main/interfaces/evse_board_support.ya
I would drop the references to MicroMegaWattBSP and PhyVersoBSP because there is no real benefit for understanding.

2024-06-20 12:51 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +This module is not mandatory for an EVSE setup using Charge Control C in EVerest. However, if EVerest is configured for an AC supply equipment with a socket connector, the module :code:`CbTarragonPlu
I think it's worth to mention that this module is generic in order to support all kinds of pluglocks and it's intended only for the lock at X9. Maybe we need to shorten the hardware chapter and reference to it.

2024-06-20 12:51 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +The Charge Control C is equipped with multiple digital inputs (DIs). To set the reference PWM for these DIs, the module :code:`CbTarragonDIs` can be used. The use of this module is optional and depen
Someone who doesn't know the function of the reference PWM, wouldn't conclude that this module is responsible to make the DI work. I think this should be made more clear. Including a reference to the hardware part?

2024-06-20 12:51 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +To test EVerest, you need to build it either natively on host Linux machine or integrate it into a firmware suitable for a specific target platform using Yocto. To build it natively, follow the instr
Not sure it's safe to make such a deep link into the EVerest documentation. No strong opinion

2024-06-20 12:51 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +The main module in a charging infrastructre EVerest setup. It manages a single EVSE (i.e., one connector for charging a car) and may control multiple connectors under some circumstances. It handles h
Not sure but maybe we should avoid the word SLAC here

2024-06-20 12:51 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +As seen from the previous configuration file, some modules are required to use EVerest with Charge Control C.
The EnergyManager is also required, but i agree don't want to describe everything. Maybe we should say the we want to "introduce the most important modules"?

2024-06-20 12:51 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +For interesting discussions and solutions to common problems, visit the EVerest community's `Zulip <https://lfenergy.zulipchat.com/>`_ channels.
We didn't defined the support workflow yet, but i would suggest to that EVerest issues not related to our BSP should be reported upstream.

2024-06-20 12:51 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +EVerest consists of multiple repositories, such as "`everest-core <https://github.com/EVerest/everest-core>`_" and "`libocpp <https://github.com/EVerest/libocpp>`_". Each repository has its own docum
I'm not sure how to document this, but maybe a table with the following columns is more helpful:
Module, Repository, Maintainer?

tbd ...

2024-06-20 14:53 UTC, t-mon requested changes

2024-06-20 14:53 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +To test EVerest, you need to build it either natively on host Linux machine or integrate it into a firmware suitable for a specific target platform using Yocto. To build it natively, follow the instr
`In order to test EVerest, ...`

2024-06-20 14:53 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +To test EVerest, you need to build it either natively on host Linux machine or integrate it into a firmware suitable for a specific target platform using Yocto. To build it natively, follow the instr
`EVerest,  which presents`

one space to much after `,`

2024-06-20 14:53 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +To set up a use case with EVerest, such as basic PWM charging, you need to create a YAML configuration file. Various example configurations, including those for software-in-the-loop tests, can be fou
`In order to` set up `an` use case with...

2024-06-20 14:53 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +The Charge Control C is equipped with multiple digital inputs (DIs). To set the reference PWM for these DIs, the module :code:`CbTarragonDIs` can be used. The use of this module is optional and depen
`In order to` set the reference PWM...

2024-06-20 14:53 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +This is the Hardware Abstraction Layer (HAL) for Charge Control C in EVerest. It implements the `evse_board_support <https://github.com/EVerest/everest-core/blob/main/interfaces/evse_board_support.ya
The term "Tarragon" in :code:`CbTarragonDriver` is the nickname of the Charge Control C hardware platform.

2024-06-20 14:53 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +This is the Hardware Abstraction Layer (HAL) for Charge Control C in EVerest. It implements the `evse_board_support <https://github.com/EVerest/everest-core/blob/main/interfaces/evse_board_support.ya
Without this module the Charge Control C can not be controlled.

2024-06-20 14:53 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +The main module in a charging infrastructre EVerest setup. It manages a single EVSE (i.e., one connector for charging a car) and may control multiple connectors under some circumstances. It handles h
charging `infrastructure`

2024-06-20 14:53 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +The main module in a charging infrastructre EVerest setup. It manages a single EVSE (i.e., one connector for charging a car) and may control multiple connectors under some circumstances. It handles h
Suggestion: try to use less (e.g., ...)

gathers all relevant data for the charging session like the delivered energy during a charging session and provides control

> Note also the `,` after the last (e.g., ...)

2024-06-20 14:53 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +As seen from the previous configuration file, some modules are required to use EVerest with Charge Control C.
some modules are required `in order` to use EVerest with Charge Control C.

2024-06-20 14:53 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +To explore EVerest further and start experimenting with its various tools, refer to the `EVerest documentation <https://everest.github.io/nightly/index.html>`_.
Suggestion: maybe start this chapter a bit different in order to prevent so many "In order to" starts :-D

Maybe something like:

`For more information and how to get started with with EVerest, understanding all the required tools and how to write your own module you can visit the official EVerest documentation <https://everest.github.io/nightly/index.html> `.

2024-06-21 08:30 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +This is the Hardware Abstraction Layer (HAL) for Charge Control C in EVerest. It implements the `evse_board_support <https://github.com/EVerest/everest-core/blob/main/interfaces/evse_board_support.ya
That the customer sees other BSP implementations?

2024-06-21 08:33 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +The Charge Control C is equipped with multiple digital inputs (DIs). To set the reference PWM for these DIs, the module :code:`CbTarragonDIs` can be used. The use of this module is optional and depen
I would just add the following:
`To set the reference PWM for these DI, which is a requirement to make them work, ....` or something like that, and would also add the reference to the hardware part if found

2024-06-21 08:34 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +To test EVerest, you need to build it either natively on host Linux machine or integrate it into a firmware suitable for a specific target platform using Yocto. To build it natively, follow the instr
But we have to I guess..

2024-06-21 08:35 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +The main module in a charging infrastructre EVerest setup. It manages a single EVSE (i.e., one connector for charging a car) and may control multiple connectors under some circumstances. It handles h
OK will do

2024-06-21 08:37 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +As seen from the previous configuration file, some modules are required to use EVerest with Charge Control C.
I do not think it is a requirement or a MUST have..

2024-06-21 08:38 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +For interesting discussions and solutions to common problems, visit the EVerest community's `Zulip <https://lfenergy.zulipchat.com/>`_ channels.
I think contribution should be a part of chargebyte/everest-chargebyte README oder CONTRIBUTING file and not in userguide?

2024-06-21 08:39 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +EVerest consists of multiple repositories, such as "`everest-core <https://github.com/EVerest/everest-core>`_" and "`libocpp <https://github.com/EVerest/libocpp>`_". Each repository has its own docum
Do we have to? It is clear that the modules under everest-chargebyte are ours and all other modules/libs are part of EVerest

2024-06-21 08:41 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +To set up a use case with EVerest, such as basic PWM charging, you need to create a YAML configuration file. Various example configurations, including those for software-in-the-loop tests, can be fou
It is actually "a" use case :P

2024-06-21 08:42 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +The Charge Control C is equipped with multiple digital inputs (DIs). To set the reference PWM for these DIs, the module :code:`CbTarragonDIs` can be used. The use of this module is optional and depen
Both "in order to" & "to", are actually grammatically correct. So I would interchange between using them throughout the document

2024-06-21 08:43 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +This is the Hardware Abstraction Layer (HAL) for Charge Control C in EVerest. It implements the `evse_board_support <https://github.com/EVerest/everest-core/blob/main/interfaces/evse_board_support.ya
I tried to make it sound a little bit more "formal" :D

2024-06-21 08:45 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +This is the Hardware Abstraction Layer (HAL) for Charge Control C in EVerest. It implements the `evse_board_support <https://github.com/EVerest/everest-core/blob/main/interfaces/evse_board_support.ya
`This module is essential for controlling the Charge Control C.` ?

2024-06-21 09:36 UTC, t-mon commented on docs/source/everest_charging_stack.rst
> +The Charge Control C is equipped with multiple digital inputs (DIs). To set the reference PWM for these DIs, the module :code:`CbTarragonDIs` can be used. The use of this module is optional and depen
One is when speaking, one is for writing if I remember correctly, but I'm OK with it :-)

2024-06-21 09:53 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +For interesting discussions and solutions to common problems, visit the EVerest community's `Zulip <https://lfenergy.zulipchat.com/>`_ channels.
Support is now part of the Troubleshooting chapter, maybe you want to reference to this chapter.

2024-06-21 09:58 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +EVerest consists of multiple repositories, such as "`everest-core <https://github.com/EVerest/everest-core>`_" and "`libocpp <https://github.com/EVerest/libocpp>`_". Each repository has its own docum
It is clear to us, but not to a EVerest newbie. So we need to write it down. The table was only a suggestion.

2024-06-21 10:02 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +This is the Hardware Abstraction Layer (HAL) for Charge Control C in EVerest. It implements the `evse_board_support <https://github.com/EVerest/everest-core/blob/main/interfaces/evse_board_support.ya
In general i agree, but not at this point of the document these are unnecessary information. This section should introduce the reader to EVerest, not how to write a BSP.

2024-06-21 10:08 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +The Charge Control C is equipped with multiple digital inputs (DIs). To set the reference PWM for these DIs, the module :code:`CbTarragonDIs` can be used. The use of this module is optional and depen
The reference PWM defines the threshold voltage for all the 12V digital inputs. It is necessary to make them work.

2024-06-21 10:11 UTC, lategoodbye commented on docs/source/everest_charging_stack.rst
> +As seen from the previous configuration file, some modules are required to use EVerest with Charge Control C.
Without it we get this flood of "Power budget expired" warnings and the user would ask why is this part of the "minimal" configuration.

2024-06-21 12:30 UTC, mooraby commented on docs/source/_static/files/bsp-only.yaml
> +# This example configuration can be used as bare minimum starting point:
I will not be  able to change the document itself because it is used in another file, but I added these bullet points in a new paragraph

2024-06-21 13:01 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +EVerest consists of multiple repositories, such as "`everest-core <https://github.com/EVerest/everest-core>`_" and "`libocpp <https://github.com/EVerest/libocpp>`_". Each repository has its own docum
I think it will be okay if I just write a note which says that everything under the EVerest project on GitHub is maintend by Pionix and the community. On the other hand, the modules under everest-chargebyte are our resposniblity.

2024-06-24 04:32 UTC, martinlukas84 commented on docs/source/everest_charging_stack.rst
> +**EvseManager** (`view on GitHub <https://github.com/EVerest/everest-core/tree/main/modules/EvseManager>`_)
To get rid of the warnings, regarding to duplicate explicit target names during the build operation, you can set a double underscore "__" after the reference text like so:

`view on GitHub <https://github.com/chargebyte/everest-chargebyte/tree/main/modules/CbSystem>`__

2024-06-24 04:37 UTC, martinlukas84 commented on docs/source/everest_charging_stack.rst
> +**EvseManager** (`view on GitHub <https://github.com/EVerest/everest-core/tree/main/modules/EvseManager>`_)
Or write the link target as link description like so:

`view CbTarragonDIs on GitHub <https://github.com/chargebyte/everest-chargebyte/tree/main/modules/CbTarragonDIs>`_

2024-06-24 06:10 UTC, barsnick requested changes

2024-06-24 06:10 UTC, barsnick commented on docs/source/everest_charging_stack.rst
> +To explore EVerest further and start experimenting with its various tools, refer to the `EVerest documentation <https://everest.github.io/nightly/index.html>`_.
You can drop the "index.html", use just https://everest.github.io/nightly/ .

2024-06-24 06:15 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +The modular software architecture promotes flexibility and customization, allowing users to configure specific charging scenarios using interchangeable modules. This architecture is integrated and co
I tend to disagree. The developer does need the information that EVerest uses MQTT under the hood, especially when developing applications that communicate with EVerest through the API module.

2024-06-24 06:16 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +The main module in a charging infrastructre EVerest setup. It manages a single EVSE (i.e., one connector for charging a car) and may control multiple connectors under some circumstances. It handles h
> handles charging logic (basic charging and HLC)

2024-06-24 06:52 UTC, barsnick commented on docs/source/everest_charging_stack.rst
> +The modular software architecture promotes flexibility and customization, allowing users to configure specific charging scenarios using interchangeable modules. This architecture is integrated and co
But the API module is not "under the hood", it translates from internals to something externally accessible via MQTT. EVerest could use RPC or protobuf or something else with auto-generated code unser the hood, and still expose MQTT via API. You're not even supposed to access the MQTT internals without generated code.

2024-06-24 06:52 UTC, barsnick commented on docs/source/everest_charging_stack.rst
> +The main module in a charging infrastructre EVerest setup. It manages a single EVSE (i.e., one connector for charging a car) and may control multiple connectors under some circumstances. It handles h
Yes, that sounds better.

2024-06-24 06:59 UTC, barsnick commented on docs/source/everest_charging_stack.rst
> +The modular software architecture promotes flexibility and customization, allowing users to configure specific charging scenarios using interchangeable modules. This architecture is integrated and co
On the other hand, you're right: For external control of the stack (if required), there is no other option than MQTT, if you don't write your own module for external control (e.g. via CAN or whatever).

2024-06-24 07:00 UTC, barsnick approved these changes

2024-06-24 07:00 UTC, mooraby commented on docs/source/everest_charging_stack.rst
> +The modular software architecture promotes flexibility and customization, allowing users to configure specific charging scenarios using interchangeable modules. This architecture is integrated and co
As for the API module: The user still needs to know that API module communicates through MQTT, so the hint that EVerest utilizes MQTT is acceptable IMO

As a developer, I also tend to disagree, as I find it useful to know how the internal MQTT topics are structured so that I can use them during debugging to read some stuff or even extend the API module.

2024-06-24 07:19 UTC, lategoodbye approved these changes

2024-06-25 09:28 UTC, merged