Add documentation for "Getting Started" chapter (refs EVEREST-950)
chargebyte/chargebyte-docs pull request #6
Opened 2024-06-21 06:24 UTC by FaHaGit

2024-06-21 07:11 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +- Power Contactor
What is the different between Contactor and Power Contactor in this context?
I would write Contactor with feedback contact.

2024-06-21 07:13 UTC, FaHaGit commented on docs/source/getting_started.rst
> +- Power Contactor
Just a misstake while merging from everest/charge_control_c

2024-06-21 07:15 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +   </div>
You can use .. figure directive with caption feature to get rid of these lines. I added a centered text alignment in custom css/cb_theme.css file. This will place figure's caption under the pic.

2024-06-21 07:50 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +- The file system basically consists of three ext4 partionions. Two partitions are used as slots for
partionions -> partitions

2024-06-21 07:51 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +  RAUC update process. The third partion is not not touched by the RAUC update process and is usualy
partion -> partition

2024-06-21 07:53 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +  used to the store update bundles, logs, etc. For more information about the RAUC update process
to store

2024-06-21 07:57 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +#. Connected the Charge Control C over Ethernet to your computer
Connect

2024-06-21 08:00 UTC, lategoodbye requested changes

2024-06-21 08:02 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +directory and create a simbolic link to it like
symbolic

2024-06-21 08:07 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +In general, the EVerest charging stack consists of different modules and each of which fulfils a
fulfills

2024-06-21 08:08 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +Each module has a specific configuration file, this file is called "mainifest.yaml" and is stored
manifest

2024-06-21 08:10 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +need to be adapted. The hardware related tasks are maninly handled by the CbTarragonDriver module.
mainly

2024-06-21 08:13 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +value. Please note if you change it directly in the "manifest.yaml" file of a mondule, the changes
module

2024-06-21 08:13 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +Here is excerpt of an EVerst configuration to change the parameter "connector_type" to
EVerest

2024-06-21 08:14 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +to adjust the EVerest configurationin a GUI. This tool must be currently installed manually on your
configuration in

2024-06-21 08:15 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +developer computer, because the recources on the board are limited.
resources

2024-06-21 08:22 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +andjust your setup to your needs. The following chapters will help you to understand the EVerest
adjust

2024-06-21 08:27 UTC, martinlukas84 requested changes
Some typos found

2024-06-24 06:49 UTC, barsnick requested changes

2024-06-24 06:49 UTC, barsnick commented on docs/source/_static/files/bsp-only.yaml
> +# no support for plug lock, no additional peripherals (RFID, meter...)
https://github.com/chargebyte/chargebyte-docs/pull/5 adds the same file. No problem if both are identical.

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +  used to the store update bundles, logs, etc. For more information about the RAUC update process
of "for storing"

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +  process is completed. The inital configuration is explained in the `Initial Configuration`_ section.
inital -> initial
```suggestion
  process is completed. The initial configuration is explained in the `Initial Configuration`_ section.
```

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +   the "Host Name (or IP address)" field (See figure :ref:`PuTTY SSH Configration <PuTTY_Serial_Configuration_2>`)..
Configration -> Configuration
```suggestion
   the "Host Name (or IP address)" field (See figure :ref:`PuTTY SSH Configuration <PuTTY_Serial_Configuration_2>`)..
```

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +#. Click on "Save" to save the configuration ans then click on "Open" to start the connection.
ans -> and
```suggestion
#. Click on "Save" to save the configuration and then click on "Open" to start the connection.
```

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +     Figure: PuTTY SSH Configration
Configration -> Configuration
```suggestion
     Figure: PuTTY SSH Configuration
```

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +#. An PuTTY Security Alert window will appear. Click on "Accept" to continue.
A PuTTY
```suggestion
#. A PuTTY Security Alert window will appear. Click on "Accept" to continue.
```
Maybe mention which security alert (host key, I guess), and why it's okay to accept.

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +Note: It is also possible to install a SSH key on the Charge Control C to log in without a
-> an SSH key
```suggestion
Note: It is also possible to install an SSH key on the Charge Control C to log in without a
```

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +password. For more information, see the TODO: Link section.
TODO 😉

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +is the config.yaml. If you take a look at the content of the configuration file, you will see that
no "the".
```suggestion
is "config.yaml". If you take a look at the content of the configuration file, you will see that
```

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +   lrwxrwxrwx 1 root root 12 Jan  1  1970 my-config.yaml  -> config.yaml
Why does bsp-only.yaml have a zero size here?

And, if I understand correctly, config.yaml is usually a symbolic link to another file, not vice versa.

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +In general, the EVerest charging stack consists of different modules and each of which fulfils a
```suggestion
In general, the EVerest charging stack consists of different modules, each of which fulfils a
```

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +need to be adapted. The hardware related tasks are maninly handled by the CbTarragonDriver module.
On Charge Control C, most hardware related tasks are handled...

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +The configuration of the CbTarragonDriver module can be found in "/usr/libexec/everest/modules/cbTarragonDriver"
This is a bit confusing, because the actual configuration is in /etc/everest/config.yaml. The manifest reflects the accepted configuration values and defines the defaults (or does it? are the defaults determined at compile time? not sure).

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +to adjust the EVerest configurationin a GUI. This tool must be currently installed manually on your
Word order:
```suggestion
to adjust the EVerest configurationin a GUI. This tool must currently be installed manually on your
```

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +Before we are starting the first charging session, it is possible to monitor the charging process
Before we start
```suggestion
Before we start the first charging session, it is possible to monitor the charging process
```

Also, a bit confusing: How can we monitor the charging process, before charging session has even started? 😉

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +16A. Now you are ready to start the first charging session with EVerest and you can plugin the IEC
-> plug in
```suggestion
16A. Now you are ready to start the first charging session with EVerest and you can plug in the IEC
```

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +be visible in the EVerest log. Per default the authentication is disabled in the bsp-only.yaml.
```suggestion
be visible in the EVerest log. Per default the authentication is disabled in the bsp-only.yaml configuration.
```

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +The last EVerest log messages after removing of the plug should look like this:
removing of the plug ->
removing the plug, or
removal of the plug

2024-06-24 06:49 UTC, barsnick commented on docs/source/getting_started.rst
> +Congratulations! You have successfully started your first charging session with the EVerest
Not only started, but also finished. So I might use the word "completed".
```suggestion
Congratulations! You have successfully completed your first charging session with the EVerest
```

2024-06-24 14:07 UTC, FaHaGit commented on docs/source/getting_started.rst
> +.. image:: _static/images/ac_pwm_charger_ccc_setup.svg
what exactly does not fit with the drawing

2024-06-24 14:30 UTC, FaHaGit commented on docs/source/_static/files/bsp-only.yaml
> +# no support for plug lock, no additional peripherals (RFID, meter...)
It should be identical. This should be the default config file from our image

2024-06-25 05:53 UTC, martinlukas84 requested changes

2024-06-25 05:53 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +Before you start setting up the hardware, please read the safty instructions in the
safety

2024-06-25 05:53 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +    Figure: PuTTY SSH Configration
Configuration

2024-06-25 05:53 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +need to be adapted. The hardware related tasks are maninly handled by the CbTarragonDriver module.
typo not solved

2024-06-25 05:53 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +and adjust your setup to your needs. The following chapters will help you understand the EVerest
two times "and"

2024-06-25 08:53 UTC, martinlukas84 requested changes
the note directive is not working because of missing : at the end.

2024-06-25 08:53 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +.. note:
.. note::

2024-06-25 08:53 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +.. note:
dito

2024-06-25 08:53 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +.. note:
dito ....

2024-06-25 10:42 UTC, martinlukas84 requested changes
Locks good to me. Just 4 points to be adapt.

2024-06-25 10:42 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +
one more empty line

2024-06-25 10:42 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +Therefore, the duty dycle should directly switch from 100% to ~26.7%. The duty cycle change indicates
cycle

2024-06-25 10:42 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +   lrwxrwxrwx 1 root root 12 Jan  1  1970 my-config.yaml  -> config.yaml
On my Tarragon bsp-only.yaml has size 1093

2024-06-25 10:42 UTC, martinlukas84 commented on docs/source/getting_started.rst
> +is the config.yaml. If you take a look at the content of the configuration file, you will see that
ping

2024-06-25 11:05 UTC, barsnick requested changes

2024-06-25 11:05 UTC, barsnick commented on docs/source/getting_started.rst
> +   It is also possible to install a SSH key on the Charge Control C to log in without a
an SSH key
```suggestion
   It is also possible to install an SSH key on the Charge Control C to log in without a
```

2024-06-25 11:05 UTC, barsnick commented on docs/source/getting_started.rst
> +   lrwxrwxrwx 1 root root 12 Jan  1  1970 my-config.yaml  -> config.yaml
This still looks unrealistic.

2024-06-25 12:58 UTC, lategoodbye commented on docs/source/getting_started.rst
> +.. image:: _static/images/ac_pwm_charger_ccc_setup.svg
Sorry, i forgot to mention. The drawing uses the contactor feedback while the configuration has no contactor feedback.

2024-06-25 13:24 UTC, lategoodbye approved these changes

2024-06-25 13:48 UTC, merged