Add Troubleshooting chapter
chargebyte/chargebyte-docs pull request #7
Opened 2024-06-21 09:50 UTC by lategoodbye

You are free to make suggestions for new questions ...

2024-06-24 06:37 UTC, martinlukas84 commented on docs/source/troubleshooting.rst
> +
We can also refer to the Github repository: https://github.com/EVerest/everest-admin-panel

2024-06-24 07:06 UTC, t-mon approved these changes

2024-06-24 07:06 UTC, t-mon commented on docs/source/troubleshooting.rst
> +Yes, for prototypes it’s possible to use the Charge Control C as DC SECC for DIN 70121 or ISO 15118.
Why as prototype but not as product? Is missing hardware the issue?

2024-06-24 07:33 UTC, lategoodbye commented on docs/source/troubleshooting.rst
> +Yes, for prototypes it’s possible to use the Charge Control C as DC SECC for DIN 70121 or ISO 15118.
My explanation so far, the Charge Control C was designed only for the AC use case, which results in the following disadvantages:
- unnecessary components like plug lock interface, AC contactor or second PLC chip
- lack of CAN interface or safety controller

2024-06-24 08:29 UTC, barsnick requested changes

2024-06-24 08:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +USB adapter.
_Note that the EVerest charging stack does not have capabilities for control via CAN yet._

(I'm not aware that it's an FAQ yet, by I guess some CAN users have that goal.

Perhaps even add:
_If you require CAN control of the charger, you need to implement your own module._

2024-06-24 08:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +use your development environment to setup your configuration file or just use a plain text editor.
setup -> set up
```suggestion
use your development environment to set up your configuration file or just use a plain text editor.
```

2024-06-24 08:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +The ISO15118-20 implementation is currently still under development and currently not included in
2x _currently_. I suggest:
```suggestion
The ISO15118-20 implementation is currently still under development and not yet included in
```

2024-06-24 08:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +Unfortunately, there are some manual steps on a development PC necessary. At first checkout the
Word order and other small details:
```suggestion
Unfortunately, some manual steps on a development PC are necessary. First, check out the
```

2024-06-24 08:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +After that you can create device model database and insert the configuration:
_a_ or _the_ device model database

2024-06-24 08:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +Then copy the device model database on Charge Control C (adapt IP address to your environment):
on -> onto the
```suggestion
Then copy the device model database onto the Charge Control C (adapt IP address to your environment):
```

2024-06-24 08:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +Finally make sure the DeviceModelDatabasePath in your EVerest configuration points to
This means the other, global configuration, so feel free to mention /etc/everest/config.yaml.

2024-06-24 08:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +EVerest already has module which takes care of Modbus communication. Please have a look at
-> _a_ module
```suggestion
EVerest already has a module which takes care of Modbus communication. Please have a look at
```

2024-06-24 08:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +`SerialCommHub <https://everest.github.io/nightly/_generated/modules/SerialCommHub.html>`_.
```suggestion
`SerialCommHub <https://everest.github.io/nightly/_generated/modules/SerialCommHub.html>`_, and let your module interact with this module via the `serial_communication_hub` interface.
```

2024-06-24 08:29 UTC, barsnick commented on docs/source/troubleshooting.rst
> +EVerest is an open-source project with a lot of modules, which is surrounded by a big community.
"surrounded" sort of works, but how about "supported"?

2024-06-24 13:19 UTC, FaHaGit requested changes

2024-06-24 13:19 UTC, FaHaGit commented on docs/source/troubleshooting.rst
> +EVerest already has module which takes care of Modbus communication. Please have a look at
"has a  module"

2024-06-24 13:19 UTC, FaHaGit commented on docs/source/troubleshooting.rst
> +for every aspect of EVerest. In order to get quick answers here are some suggestions:
not sure, but I would add a comma "answers, here are some"

2024-06-25 11:15 UTC, barsnick requested changes
Minor nits, otherwise fine.

2024-06-25 11:15 UTC, barsnick commented on docs/source/troubleshooting.rst
> +I want to control EVerest via CAN, how can i achieve this?
Capital I:
```suggestion
I want to control EVerest via CAN, how can I achieve this?
```

2024-06-25 11:15 UTC, barsnick commented on docs/source/troubleshooting.rst
> +But the Charge Control C was designed for AC use case in mind.
I would say "with [something] in mind:
```suggestion
But the Charge Control C was designed with the AC use case in mind.
```

2024-06-26 07:25 UTC, merged